Trying my hands on with numpy for the first time. So I'm going to go through some basics in preparation for the programming assignments. I will try to keep this updated with more hands on of numpy and related packages as I go further.

Import the package first!

In [16]:
import numpy as np

Arrays are very basic construct within numpy. Here is how to define one.

In [19]:
arr = np.array([1, 2, 3, 4])
print(arr)
print("Shape of the array is: ", arr.shape)

[1 2 3 4]
Shape of the array is:  (4,)


Shape of the array is nothing but the dimension of the array. We get that by accessing the `shape` value of the array. The list `[1, 2, 3, 4]` might look like a 1-dimensional vector with a dimension of 1x4. But it is not. Lists like `[1, 2, 3 ,4]` are not considered vectors. We rarely deal with this type of array while working on the problems.

In [25]:
# This is a 2-D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of 2D array:", arr2d.shape)

# A 3-D array. This kind of array is often used in image processing
# Each pixel containing three 3 8-bit values for Red, Green and Blue
arr3d = np.array([[[0x1a, 0x1b, 0x1c], [0x1d, 0x1e, 0x1f], [0x11, 0x12, 0x13]],
                 [[0x2a, 0x2b, 0x2c], [0x2d, 0x2e, 0x2f], [0x21, 0x22, 0x23]],
                 [[0x3a, 0x3b, 0x3c], [0x2d, 0x2e, 0x2f], [0x31, 0x32, 0x33]]])

print("Shape of 3-D array:", arr3d.shape)

Shape of 2D array: (2, 3)
Shape of 3-D array: (3, 3, 3)


Lets try some built-in functions to create numpy arrays...Keeping the [numpy docs](https://docs.scipy.org/doc/numpy-1.10.1/genindex.html) handy for quick reference.

In [54]:
# np.zeros takes three parameters: shape, dtype, order.
# Datatype defaults to float and order defaults to C-style. 

# this creates a 4x3 matrix filled with 0.0
zeros = np.zeros((4, 3))

print("\n====Zeros====")
print(zeros)
print("Type:{}, Shape:{}, value type:{}".format(type(zeros), zeros.shape, zeros.dtype))

print("\n====Ones====")
ones = np.ones(3, dtype=np.int)
anotherOnes1D = np.ones((3,), dtype=int) # Same as above, but uses int instead of np.int

print(ones, ones.shape, ones.dtype)

print("\n====Identity matrix====")
# np.identity returns a nxn identity matrix.
# Like most np calls, we can specify the dtype here as well.
iden = np.identity(3)
print(iden)

print("\n====Identity matrix using eye====")
# This is advanced version of np.identity
# lets us control the shape as well as the diagonal
# axis to start setting 1s.
eye = np.eye(3, 2, dtype=int)
print(eye)

print("\n====Random matrices====")
# takes a variable length argument list for the dimensions
# fills the output array with values from the uniform
# distribution between 0..1
randArray = np.random.rand(4, 3)
print("Uniform distribution")
print(randArray)

# randint takes the lower and upper limits for the random int
# and size of the array
randIntArray = np.random.randint(10, size=(3, 2))
print("\nRandom Ints")
print(randIntArray)


====Zeros====
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Type:<class 'numpy.ndarray'>, Shape:(4, 3), value type:float64

====Ones====
[1 1 1] (3,) int64

====Identity matrix====
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

====Identity matrix using eye====
[[1 0]
 [0 1]
 [0 0]]

====Random matrices====
Uniform distribution
[[0.21216697 0.10413436 0.458502  ]
 [0.42438921 0.59061434 0.24831119]
 [0.15178391 0.50220867 0.83642531]
 [0.62141571 0.77486848 0.66162555]]

Random Ints
[[0 6]
 [4 5]
 [6 1]]


Now lets try simple operations on the numpy objects. 

In [63]:
# transpose a matrix
data = np.random.randint(10, size=(3, 4))

print("Data:\n", data)
print("Data transpose:\n", data.T)

Data:
 [[6 1 4 9]
 [8 9 2 1]
 [8 4 9 7]]
Data transpose:
 [[6 8 8]
 [1 9 4]
 [4 2 9]
 [9 1 7]]


Reshaping is another frequently performed operation across all machine learning problems. An example use case is image processing. Consider the image with resolution 32x32 px. It is digitally represented as 32x32x3 matrix (32x32 by of RGB values). It is often reshaped into one dimension array of 32\*32\*3x1 for faster access and easier handling.

In [64]:
print("Data:")
print(data)
print("\nReshaped data:")
print(data.reshape((4, 3)))
print("\nReshaping again:")
print(data.reshape((1,12)))
print("\nReshaping again:")
print(data.reshape(1, 12).reshape(2, 6))

Data:
[[6 1 4 9]
 [8 9 2 1]
 [8 4 9 7]]

Reshaped data:
[[6 1 4]
 [9 8 9]
 [2 1 8]
 [4 9 7]]

Reshaping again:
[[6 1 4 9 8 9 2 1 8 4 9 7]]

Reshaping again:
[[6 1 4 9 8 9]
 [2 1 8 4 9 7]]


In [65]:
%%html
<style>
    table {
        display: inline-block
    }
</style>

Trying out some math operations on the numpy arrays as we will often need to solve equations in building a machine learning models. Numpy has equivalent math functions for almost all of the math operations that python natively supports.

Here are some examples:

| Operation | Numpy equivalent |
|------------|------------------|
|a = b + c  | a = np.add(b, c) |
|a = b - c  | a = np.subtract(b, c)|
|a = b * c  | a = np.multiply(b, c) |
|a = sum(nums) | a = np.sum(nums) |
|a = max(nums) | a = np.max(nums) |
|matrix multiply | a = np.dot(b, c)|

The numpy equivalents are highly optimized to vectorize the operations that runs much much faster than if the operation was implemented with for loop.